version: "3.9"

services:
  db:
    image: postgres:16
    container_name: my_backend_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # backend:
  #   build: .
  #   container_name: my_backend_app
  #   restart: always
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
      
  #   ports:
  #     - "3000:3000"
  #   command: ["cargo", "run"]
  #   volumes:
  #     - .:/app
  #   working_dir: /app

volumes:
  postgres_data:
